import 'package:flutter/material.dart';

class Product {
  final String id;
  final String title, description;
  final List<String> images;
  final List<Color> colors;
  final double rating, price;
  final bool  isPopular;
  int quantity;

  Product({
    required this.id,
    required this.images,
    required this.colors,
    this.rating = 0.0,
    this.isPopular = false,
    required this.title,
    required this.price,
    required this.description,
    required this.quantity,
  });
}

// Our demo Products

List<Product> demoProducts = [
  Product(
    id: "1",
    images: [
      "assets/images/man jacket.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 207, 142, 57),
    ],
    title: "Man Jacket",
    price: 1500,
    description: "Orange Jacket For winter and mountaining for man...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "2",
    images: [
      "assets/images/ps4_console_white_1.png",
      "assets/images/ps4_console_white_2.png",
      "assets/images/ps4_console_white_3.png",
      "assets/images/ps4_console_white_4.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Wireless Controller for PS4™",
    price: 400,
    description: "Wireless Controller for PS4™ gives you what you want in your gaming from over precision control your games to sharing …",
    rating: 4.8,
    isPopular: false,
    quantity: 1,
  ),
  Product(
    id: "3",
    images: [
      "assets/images/t-shert.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 230, 30, 233),
    ],
    title: "Woman T-shirt",
    price: 300,
    description: "Woman T-shirt (casual dress, Light Pink)...",
    rating: 4.8,
    isPopular: false,
    quantity: 1,
  ),
  Product(
    id: "4",
    images: ["assets/images/Image Popular Product 2.png"],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Nike Sport White - Men Pant",
    price: 300,
    description: "Running Sports Shorts for Men with Mobile Phone Pocket Light Weight Quick Dry Fabric for Gym Athletic",
    rating: 4.1,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "5",
    images: [
      "assets/images/OnePlus 11R 5G.jpg",
      "assets/images/OnePlus 11R 5G 2.jpg",
      "assets/images/OnePlus 11R 5G 3.jpg",
      "assets/images/OnePlus 11R 5G 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.blueGrey,
    ],
    title: "OnePlus 11R 5G",
    price: 30000,
    description: "OnePlus 11R 5G (Galactic Silver, 8GB RAM, 128GB Storage)",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "6",
    images: [
      "assets/images/Poco C65 .jpg",
      "assets/images/Poco C65 2.jpg",
      "assets/images/Poco C65 3.jpg",
      "assets/images/Poco C65 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 94, 179, 249),
    ],
    title: "Poco C65",
    price: 10000,
    description: "POCO C65 (Pastel Blue 6GB RAM 128GB Storage)",
    rating: 4.8,
    isPopular: false,
    quantity: 1,
  ),
  Product(
    id: "7",
    images: ["assets/images/glap.png"],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.black,
    ],
    title: "Gloves XC Omega - Polygon",
    price: 400,
    description: "SLOVIC Gym Gloves with Wrist Support & Hexagon Grips | for Men & Women | Suitable for Workout & Weightlifting | Breathable Fabric | Soft Cushion Pads - Size Small",
    rating: 4.1,
    isPopular: false,
    quantity: 1,
  ),
  Product(
    id: "8",
    images: [
      "assets/images/New Balance 990.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "New Balance 990 Shoes-Man",
    price: 900,
    description: "White New Balance 990 (Both Casual and Sport shoes - Man)...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "9",
    images: [
      "assets/images/watch.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 39, 119, 42),
    ],
    title: "Titan Watch",
    price: 20000,
    description: "Titan Metal Mechanicals Analog Green Dial and Band Men's Stainless Steel Watch...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "10",
    images: [
      "assets/images/white sneaker.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "White Sneaker-Man",
    price: 1100,
    description: "Campus Casual Camp-Denver White Men's Sneakers | Secure Lace-Up Closure, Water-Resistant Upper, and Soft EVA Insole in Stylish Sneakers for Men and Boys...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "11",
    images: [
      "assets/images/pants.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.black,
    ],
    title: "Black Pants-Man",
    price: 600,
    description: "Black Pants (Party wear, Office, and Casual also) - Man...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "12",
    images: ["assets/images/wireless headset.png"],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.black,
    ],
    title: "Logitech Head",
    price: 14000,
    description: "Logitech Lightspeed Wireless Gaming Headset with Suspension Over Ear Headband, LIGHTSYNC RGB, Blue VO!CE mic Technology and PRO-G Audio Drivers - Black",
    rating: 4.1,
    quantity: 1,
  ),
  Product(
    id: "13",
    images: [
      "assets/images/OnePlus Nord 2 5G.jpg",
      "assets/images/OnePlus Nord 2 5G 2.jpg",
      "assets/images/OnePlus Nord 2 5G 3.jpg",
      "assets/images/OnePlus Nord 2 5G 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.grey,
    ],
    title: "OnePlus Nord 2 5G",
    price: 34000,
    description: "OnePlus OnePlus Nord 2 5G (Gray Sierra, 12GB RAM, 256GB Storage)",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "14",
    images: [
      "assets/images/lehenga.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 25, 6, 130),
    ],
    title: "Blue Lehenga-Women",
    price: 400,
    description: "Blue Lehenga For Party women dress...",
    rating: 4.8,
    isPopular: false,
    quantity: 1,
  ),
  Product(
    id: "15",
    images: [
      "assets/images/Poco M6 5G.jpg",
      "assets/images/Poco M6 5G 2.jpg",
      "assets/images/Poco M6 5G 3.jpg",
      "assets/images/Poco M6 5G 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 82, 77, 237),
    ],
    title: "Poco M6 5G",
    price: 10000,
    description: "POCO M6 5G (Orion Blue, 6GB RAM, 128GB Storage)",
    rating: 4.8,
    isPopular: false,
    quantity: 1,
  ),
  Product(
    id: "16",
    images: [
      "assets/images/ps4_console_blue_1.png",
      "assets/images/ps4_console_blue_2.png",
      "assets/images/ps4_console_blue_3.png",
      "assets/images/ps4_console_blue_4.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      Colors.white,
      const Color(0xFFDECB9C),
      const Color(0xFF836DB8),
    ],
    title: "Wireless Controller for PS4™",
    price: 500,
    description: "Wireless Controller for PS4™ gives you what you want in your gaming from over precision control your games to sharing …",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "17",
    images: [
      "assets/images/Air Jordan.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.brown,
    ],
    title: "Air Jordan Shoes-Man",
    price: 1000,
    description: "Air Jordan Brown Sport Shoes - Man",
    rating: 4.8,
    isPopular: false,
    quantity: 1,
  ),
  Product(
    id: "18",
    images: [
      "assets/images/kurta.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Women's Kurta",
    price: 800,
    description: "Green Kurta for festival - Woman...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "19",
    images: [
      "assets/images/iPhone 15.jpg",
      "assets/images/iPhone 15 2.jpg",
      "assets/images/iPhone 15 3.jpg",
      "assets/images/iPhone 15 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.black,
    ],
    title: "iPhone 15",
    price: 150000,
    description: "Apple iPhone 15 (128 GB) - Black",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "20",
    images: [
      "assets/images/OnePlus Nord 2 .jpg",
      "assets/images/OnePlus Nord 2 4.jpg",
      "assets/images/OnePlus Nord 2 3.jpg",
      "assets/images/OnePlus Nord 2 2.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 49, 114, 51),
    ],
    title: "OnePlus Nord 2 (Green Woods)",
    price: 64.99,
    description: "OnePlus Nord 2 5G (Green Woods, 12GB RAM, 256GB Storage)",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "21",
    images: [
      "assets/images/Iphone 13.jpg",
      "assets/images/iphone 13 2.jpg",
      "assets/images/iphone 13 3.jpg",
      "assets/images/iphone 13 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 227, 88, 134),
    ],
    title: "iPhone 13",
    price: 64000,
    description: "Apple iPhone 13 (128GB) - Pink",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "22",
    images: [
      "assets/images/OnePlus 9 5G.jpg",
      "assets/images/OnePlus 9 5G 2.jpg",
      "assets/images/OnePlus 9 5G 3.jpg",
      "assets/images/OnePlus 9 5G 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      Colors.white,
      const Color(0xFFDECB9C),
      const Color(0xFF836DB8),
    ],
    title: "OnePlus 9 5G",
    price: 15000,
    description: "OnePlus 9 5G Winter Mist 12GB RAM 256GB Storage",
    rating: 4.8,
    isPopular: false,
    quantity: 1,
  ),
  Product(
    id: "23",
    images: ["assets/images/tshirt.png"],
    colors: [
      Colors.white,
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color(0xFFF6625E),
    ],
    title: "Adidas - Men Tshirt",
    price: 400,
    description: "Adidas Men's Regular Fit T-Shirt (Orange)",
    rating: 4.1,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "24",
    images: ["assets/images/shoes2.png"],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.black,
    ],
    title: "Nike - Men Shoes",
    price: 550,
    description: "Nike Mens Revolution 7Running Shoe, sport shoe, tracking shoe...",
    rating: 4.1,
    isPopular: false,
    quantity: 1,
  ),
  Product(
    id: "25",
    images: ["assets/images/product 1 image.png"],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      Colors.white,
      const Color.fromARGB(255, 234, 187, 68),
    ],
    title: "Men Tshirt",
    price: 200,
    description: "Casual Men's T-shirt (yellow)...",
    rating: 4.1,
    quantity: 1,
  ),
];

List<Product> smartphones = [
  Product(
    id: "1",
    images: [
      "assets/images/OnePlus Nord 2 5G.jpg",
      "assets/images/OnePlus Nord 2 5G 2.jpg",
      "assets/images/OnePlus Nord 2 5G 3.jpg",
      "assets/images/OnePlus Nord 2 5G 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.grey,
    ],
    title: "OnePlus Nord 2 5G",
    price: 34000,
    description: "OnePlus OnePlus Nord 2 5G (Gray Sierra, 12GB RAM, 256GB Storage)",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "2",
    images: [
      "assets/images/Iphone 13.jpg",
      "assets/images/iphone 13 2.jpg",
      "assets/images/iphone 13 3.jpg",
      "assets/images/iphone 13 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 239, 73, 128),
    ],
    title: "iPhone 13",
    price: 64000,
    description: "Apple iPhone 13 (128GB) - Pink",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "3",
    images: [
      "assets/images/OnePlus 9 5G.jpg",
      "assets/images/OnePlus 9 5G 2.jpg",
      "assets/images/OnePlus 9 5G 3.jpg",
      "assets/images/OnePlus 9 5G 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      Colors.white,
      const Color(0xFFDECB9C),
      const Color(0xFF836DB8),
    ],
    title: "OnePlus 9 5G",
    price: 15000,
    description: "OnePlus 9 5G Winter Mist 12GB RAM 256GB Storage",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "4",
    images: [
      "assets/images/iPhone 15.jpg",
      "assets/images/iPhone 15 2.jpg",
      "assets/images/iPhone 15 3.jpg",
      "assets/images/iPhone 15 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.black,
    ],
    title: "iPhone 15",
    price: 150000,
    description: "Apple iPhone 15 (128 GB) - Black",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "5",
    images: [
      "assets/images/OnePlus Nord 2 .jpg",
      "assets/images/OnePlus Nord 2 4.jpg",
      "assets/images/OnePlus Nord 2 3.jpg",
      "assets/images/OnePlus Nord 2 2.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 49, 114, 51),
    ],
    title: "OnePlus Nord 2 (Green Woods)",
    price: 64.99,
    description: "OnePlus Nord 2 5G (Green Woods, 12GB RAM, 256GB Storage)",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "6",
    images: [
      "assets/images/iphone 13 Blue.jpg",
      "assets/images/iphone 13 blue 2.jpg",
      "assets/images/iphone 13 blue 3.jpg",
      "assets/images/iphone 13 blue 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 18, 76, 124),
    ],
    title: "iPhone 13 Blue",
    price: 64000,
    description: "Apple iPhone 13 (128GB) - Blue",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "7",
    images: [
      "assets/images/OnePlus 11R 5G.jpg",
      "assets/images/OnePlus 11R 5G 2.jpg",
      "assets/images/OnePlus 11R 5G 3.jpg",
      "assets/images/OnePlus 11R 5G 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.blueGrey,
    ],
    title: "OnePlus 11R 5G",
    price: 30000,
    description: "OnePlus 11R 5G (Galactic Silver, 8GB RAM, 128GB Storage)",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "8",
    images: [
      "assets/images/Poco C65 .jpg",
      "assets/images/Poco C65 2.jpg",
      "assets/images/Poco C65 3.jpg",
      "assets/images/Poco C65 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 94, 179, 249),
    ],
    title: "Poco C65",
    price: 10000,
    description: "POCO C65 (Pastel Blue 6GB RAM 128GB Storage)",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "9",
    images: [
      "assets/images/Poco M6 5G.jpg",
      "assets/images/Poco M6 5G 2.jpg",
      "assets/images/Poco M6 5G 3.jpg",
      "assets/images/Poco M6 5G 4.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 82, 77, 237),
    ],
    title: "Poco M6 5G",
    price: 10000,
    description: "POCO M6 5G (Orion Blue, 6GB RAM, 128GB Storage)",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "10",
    images: [
      "assets/images/Redmi Phone.jpg",
      "assets/images/Redmi Phone 2.jpg",
      "assets/images/Redmi Phone 3.jpg",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Redmi 12 5G",
    price: 12000,
    description: "Redmi 12 5G Moonstone Silver 6GB RAM 128GB ROM",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
];

List<Product> fashions = [
  Product(
    id: "1",
    images: [
      "assets/images/Air Jordan.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.brown,
    ],
    title: "Air Jordan Shoes-Man",
    price: 1000,
    description: "Air Jordan Brown Sport Shoes - Man",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "2",
    images: [
      "assets/images/kurta.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Women's Kurta",
    price: 800,
    description: "Green Kurta for festival - Woman...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "3",
    images: [
      "assets/images/lehenga.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 25, 6, 130),
    ],
    title: "Blue Lehenga-Women",
    price: 400,
    description: "Blue Lehenga For Party women dress...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "4",
    images: [
      "assets/images/man jacket.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 207, 142, 57),
    ],
    title: "Man Jacket",
    price: 1500,
    description: "Orange Jacket For winter and mountaining for man...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "5",
    images: [
      "assets/images/New Balance 990.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "New Balance 990 Shoes-Man",
    price: 900,
    description: "White New Balance 990 (Both Casual and Sport shoes - Man)...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "6",
    images: [
      "assets/images/pants.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.black,
    ],
    title: "Black Pants-Man",
    price: 600,
    description: "Black Pants (Party wear, Office, and Casual also) - Man...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "7",
    images: [
      "assets/images/t-shert.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 230, 30, 233),
    ],
    title: "Woman T-shirt",
    price: 300,
    description: "Woman T-shirt (casual dress, Light Pink)...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "8",
    images: [
      "assets/images/t-shirt.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.brown,
    ],
    title: "Man T-shirt",
    price: 250,
    description: "Man T-shirt (Casual dress, Brown)...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "9",
    images: [
      "assets/images/watch.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      const Color.fromARGB(255, 39, 119, 42),
    ],
    title: "Titan Watch",
    price: 20000,
    description: "Titan Metal Mechanicals Analog Green Dial and Band Men's Stainless Steel Watch...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
  Product(
    id: "10",
    images: [
      "assets/images/white sneaker.png",
      ],
    colors: [
      const Color(0xFFF6625E),
      const Color(0xFF836DB8),
      const Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "White Sneaker-Man",
    price: 1100,
    description: "Campus Casual Camp-Denver White Men's Sneakers | Secure Lace-Up Closure, Water-Resistant Upper, and Soft EVA Insole in Stylish Sneakers for Men and Boys...",
    rating: 4.8,
    isPopular: true,
    quantity: 1,
  ),
];