// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP3y2OeJdLxCEjlJxz3gpP0oJreji7KHI',
    appId: '1:829068960760:web:cc5e5c4e698796c9b8ac0d',
    messagingSenderId: '829068960760',
    projectId: 'e-commerce-app-3c194',
    authDomain: 'e-commerce-app-3c194.firebaseapp.com',
    storageBucket: 'e-commerce-app-3c194.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP6rT0IDJfFkJ_Gy3cThPtcPOJ7K732k4',
    appId: '1:829068960760:android:7efbc0cb38ebbd3eb8ac0d',
    messagingSenderId: '829068960760',
    projectId: 'e-commerce-app-3c194',
    storageBucket: 'e-commerce-app-3c194.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAclRB89IhHw6kiKvgJhKEBLcdf_Ar3w4',
    appId: '1:829068960760:ios:0a7fd1b1d3fbb81bb8ac0d',
    messagingSenderId: '829068960760',
    projectId: 'e-commerce-app-3c194',
    storageBucket: 'e-commerce-app-3c194.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAclRB89IhHw6kiKvgJhKEBLcdf_Ar3w4',
    appId: '1:829068960760:ios:0a7fd1b1d3fbb81bb8ac0d',
    messagingSenderId: '829068960760',
    projectId: 'e-commerce-app-3c194',
    storageBucket: 'e-commerce-app-3c194.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP3y2OeJdLxCEjlJxz3gpP0oJreji7KHI',
    appId: '1:829068960760:web:20f891794a266e4ab8ac0d',
    messagingSenderId: '829068960760',
    projectId: 'e-commerce-app-3c194',
    authDomain: 'e-commerce-app-3c194.firebaseapp.com',
    storageBucket: 'e-commerce-app-3c194.firebasestorage.app',
  );

}